name: Node.js Package

on:
  push:
    branches:
      - testing-story-commands

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url:  
          scope: '@pig-test'
          always-auth: true
      - run: npm install --prefix ./common-components
      - run: npm run --prefix ./common-components
      - run: npm run build --prefix ./common-components
      - name: StoryBook Build
        run : |
            npm run build-storybook --prefix ./common-components
      - name: root directory
        run: cd ..
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_NPM_TOKEN_2 }}
      
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'   
          SOURCE_DIR: 'common-components\storybook-static'

