name: Node.js Package

on:
  push:
    branches:
      - my-publish-pk

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url:  
          scope: '@pig-test'
          always-auth: true
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: 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
