name: Node.js Package

on:
  push:
    branches:
      - master-pkg

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@pig-test'
      - run: yarn install
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: 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
